spring:
  datasource:
    url: jdbc:mysql://${HOST:localhost}:3306/${MYSQL_DATABASE:api_db}?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:pass}
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080
  servlet:
    context-path: /api

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 60 minutes duration by default: 12 * 5 minutes * 60 seconds * 1000 miliseconds
