export const initialPromiseTable = {
    id: null,
    round: null,
    activity_1_ch: null,
    activity_2_ch: null,
    activity_3_ch: null,
    activity_4_ch: null,
    point_1_ch: null,
    point_2_ch: null,
    point_3_ch: null,
    point_4_ch: null,
    activity_1_ch_user: null,
    activity_2_ch_user: null,
    activity_3_ch_user: null,
    activity_4_ch_user: null,
    comment_ch: null,
    activity_1_tr: null,
    activity_2_tr: null,
    activity_3_tr: null,
    point_1_tr: null,
    point_2_tr: null,
    point_3_tr: null,
    activity_1_tr_user: null,
    activity_2_tr_user: null,
    activity_3_tr_user: null,
    comment_tr: null,
    activity_tr_time: null
}
